# Generated by Django 2.2.3 on 2019-07-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=12)),
                ('price_range', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('possession', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('flat_type', models.CharField(max_length=20)),
            ],
        ),
    ]
