# Generated by Django 2.2.3 on 2019-07-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190712_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='flat_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='possession',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='price_range',
            field=models.CharField(max_length=50),
        ),
    ]
