# Generated by Django 2.2.3 on 2019-07-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190712_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_details',
            name='email',
        ),
    ]
