# Generated by Django 2.2.3 on 2019-07-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_property_details1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_details',
        ),
    ]
