# Generated by Django 2.2.3 on 2019-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_property_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_first_name', models.CharField(default='', max_length=20)),
                ('owner_last_name', models.CharField(default='', max_length=20)),
                ('owner_email', models.EmailField(default='NULL', max_length=254)),
                ('owner_contact_no', models.CharField(default='enter_phNo', max_length=12)),
                ('appt_desc', models.CharField(max_length=5000)),
                ('cust_first_name', models.CharField(default='Enter_name', max_length=100)),
                ('cust_last_name', models.CharField(default='Enter_name', max_length=50)),
                ('cust_email', models.EmailField(default='NULL', max_length=254)),
                ('cust_contact_no', models.CharField(default='enter_phNo', max_length=12)),
            ],
        ),
    ]
