# Generated by Django 2.2.3 on 2019-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_buyupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details1',
            name='img',
            field=models.ImageField(default='Not NULL', upload_to='app1/Media/'),
        ),
    ]
