# Generated by Django 2.2.3 on 2019-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_property_details1_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details1',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='app1/Media/'),
        ),
    ]
