# Generated by Django 2.2.3 on 2019-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details1',
            name='img',
            field=models.ImageField(blank=True, upload_to='app1/Media/'),
        ),
    ]
